// Tiny DSL for declaring n8n workflows in code. scripts/build_workflows.mjs
// turns these declarations into importable JSON with fixed ids.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const PG_CREDENTIAL = { postgres: { id: 'PgCitizenBot0001', name: 'citizen_bot' } };

export const IDS = {
  router: 'CoreRouter000001',
  send: 'CoreSend00000001',
  llm: 'CoreLlm000000001',
  alert: 'CoreAlert0000001',
  error: 'CoreError0000001',
  harness: 'CoreHarness00001',
  echo: 'SvcEcho000000001',
  template: 'SvcTemplate00001',
  mela: 'SvcMela000000001',
  syncMela: 'SyncMela00000001',
};

// Source of a module from n8n/src, with the CommonJS export line removed.
export function moduleSource(rel) {
  const text = fs.readFileSync(path.join(SRC, rel), 'utf8');
  return text.replace(/^if \(typeof module !== 'undefined'\)[\s\S]*$/m, '').trimEnd();
}

function nodeId(name) {
  // stable, readable node ids derived from the node name
  return `n-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
}

export class Workflow {
  constructor(id, name, settings = {}) {
    this.id = id;
    this.name = name;
    this.nodes = [];
    this.connections = {};
    this.settings = { executionOrder: 'v1', ...settings };
    this.x = 0;
  }

  add(name, type, typeVersion, parameters, extra = {}) {
    const n = { id: nodeId(name), name, type, typeVersion, position: extra.position || [this.x, extra.y || 0], parameters, ...extra };
    delete n.y;
    this.x += 240;
    this.nodes.push(n);
    return name;
  }

  code(name, { modules = [], main, mode = 'runOnceForEachItem' }, extra = {}) {
    const jsCode = [
      '// GENERATED by scripts/build_workflows.mjs from n8n/src - do not edit in the n8n UI.',
      ...modules.map((m) => `// ---- ${m}\n${moduleSource(m)}`),
      '// ---- main',
      main.trim(),
    ].join('\n\n');
    return this.add(name, 'n8n-nodes-base.code', 2, { mode, jsCode }, extra);
  }

  pg(name, query, paramsExpr, extra = {}) {
    return this.add(name, 'n8n-nodes-base.postgres', 2.6, {
      operation: 'executeQuery', query, options: { queryReplacement: paramsExpr },
    }, { credentials: PG_CREDENTIAL, ...extra });
  }

  execute(name, workflowIdExpr, { wait = true, onError } = {}, extra = {}) {
    return this.add(name, 'n8n-nodes-base.executeWorkflow', 1.3, {
      source: 'database',
      workflowId: { __rl: true, mode: 'id', value: workflowIdExpr },
      workflowInputs: { mappingMode: 'defineBelow', value: {} },
      mode: 'once',
      options: { waitForSubWorkflow: wait },
    }, { ...(onError ? { onError } : {}), ...extra });
  }

  trigger(name = 'When Called') {
    return this.add(name, 'n8n-nodes-base.executeWorkflowTrigger', 1.2, { inputSource: 'passthrough' });
  }

  switchOn(name, outputs, expr) {
    return this.add(name, 'n8n-nodes-base.switch', 3.4, { mode: 'expression', numberOutputs: outputs, output: expr });
  }

  connect(from, to, fromOutput = 0) {
    const c = (this.connections[from] = this.connections[from] || { main: [] });
    while (c.main.length <= fromOutput) c.main.push([]);
    c.main[fromOutput].push({ node: to, type: 'main', index: 0 });
  }

  chain(...names) {
    for (let i = 0; i + 1 < names.length; i++) this.connect(names[i], names[i + 1]);
  }

  toJSON() {
    return {
      id: this.id,
      name: this.name,
      active: false,
      nodes: this.nodes,
      connections: this.connections,
      settings: this.settings,
      pinData: {},
      meta: { generatedBy: 'scripts/build_workflows.mjs' },
    };
  }
}
